/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.util.logging.Logger;
import model.AkunPengguna;
import database.DatabaseConnection;

/**
 *
 * @author aliya
 */

public class AdminForm extends javax.swing.JFrame {
    private static final Logger logger = Logger.getLogger(AdminForm.class.getName());
    private AkunPengguna akunLogin;
    
    // Konstruktor dipanggil setelah login
    public AdminForm(AkunPengguna akun) {
        initComponents();
        this.akunLogin = akun;
        setTitle("Admin Dashboard - " + akunLogin.getUsername());

        // Contoh: tampilkan nama user di title jendela
        setTitle("Admin Dashboard - " + akunLogin.getUsername());
    }
    
    // Constructor default (NetBeans GUI)
      public AdminForm() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSubmitMasyarakat3 = new javax.swing.JButton();
        btnSubmitMasyarakat2 = new javax.swing.JButton();
        btnSubmitMasyarakat = new javax.swing.JButton();
        btnSubmitMasyarakat1 = new javax.swing.JButton();
        Username1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 465));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitMasyarakat3.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat3.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat3.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat3.setText("KELUAR");
        btnSubmitMasyarakat3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 120, 30));

        btnSubmitMasyarakat2.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat2.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat2.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat2.setText("KELOLA STAKEHOLDER");
        btnSubmitMasyarakat2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 200, 30));

        btnSubmitMasyarakat.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat.setText("KELOLA LAPORAN");
        btnSubmitMasyarakat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakatActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 200, 30));

        btnSubmitMasyarakat1.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat1.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat1.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat1.setText("KELOLA AKUN PENGGUNA");
        btnSubmitMasyarakat1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, 200, 30));

        Username1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 50)); // NOI18N
        Username1.setForeground(new java.awt.Color(0, 102, 102));
        Username1.setText("Hi Admin!");
        Username1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 350, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/5.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakatActionPerformed
        KelolaLaporanForm kelolaLaporan = new KelolaLaporanForm();
        kelolaLaporan.setVisible(true);
        this.dispose();
        new KelolaLaporanForm("superadmin").setVisible(true);

    }//GEN-LAST:event_btnSubmitMasyarakatActionPerformed

    private void btnSubmitMasyarakat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat1ActionPerformed

        KelolaPenggunaForm kelolaPengguna = new KelolaPenggunaForm();
        kelolaPengguna.setVisible(true);
        this.dispose(); // Tutup form admin
    }//GEN-LAST:event_btnSubmitMasyarakat1ActionPerformed

    private void btnSubmitMasyarakat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat2ActionPerformed
        KelolaStakeholderForm kelolaStakeholder = new KelolaStakeholderForm();
        kelolaStakeholder.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakat2ActionPerformed

    private void btnSubmitMasyarakat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat3ActionPerformed
       int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin keluar ke menu login?",
            "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION
    );
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakat3ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username1;
    private javax.swing.JButton btnSubmitMasyarakat;
    private javax.swing.JButton btnSubmitMasyarakat1;
    private javax.swing.JButton btnSubmitMasyarakat2;
    private javax.swing.JButton btnSubmitMasyarakat3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
