/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.LaporanDAO;
import dao.LaporanDAOImpl;
import model.Laporan;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JComboBox;


/**
 *
 * @author aliya
 */
public class KelolaLaporanForm extends javax.swing.JFrame {
    private static final Logger logger = Logger.getLogger(AdminForm.class.getName());
    private LaporanDAO laporanDAO;
    private DefaultTableModel model;
    private javax.swing.JComboBox<String> comboStatusLaporan;
    private String currentRole = ""; // ✅ Tambahkan ini untuk menyimpan role aktif


    
    public KelolaLaporanForm(String role) {
    initComponents();
    laporanDAO = new LaporanDAOImpl();
    model = (DefaultTableModel) jTable1.getModel();
    loadData();
    this.currentRole = role;




    }
    public KelolaLaporanForm() {
        initComponents();
        laporanDAO = new LaporanDAOImpl();
        model = (DefaultTableModel) jTable1.getModel();
        loadData();
        comboStatusLaporan = new javax.swing.JComboBox<>(new String[] {
    "Baru", "Diproses", "Selesai"
});
        
    }

    private void loadData() {
        model.setRowCount(0);
        List<Laporan> list = laporanDAO.getAllLaporan();
        for (Laporan l : list) {
            model.addRow(new Object[]{
                l.getIdPelapor(),
                l.getTanggalLaporan(),
                l.getLokasiLaporan(),
                l.getJenisMasalah(),
                l.getDeskripsi(),
                l.getStatusLaporan(),
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSubmitMasyarakat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Stakeholder = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 465));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTambah.setBackground(new java.awt.Color(0, 102, 102));
        btnTambah.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, 30));

        btnEdit.setBackground(new java.awt.Color(0, 102, 102));
        btnEdit.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 90, 30));

        btnHapus.setBackground(new java.awt.Color(0, 102, 102));
        btnHapus.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 90, 30));

        btnSubmitMasyarakat.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat.setText("KELUAR");
        btnSubmitMasyarakat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakatActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 90, 30));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setForeground(new java.awt.Color(0, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Laporan", "Tanggal Laporan", "Lokasi Laporan", "Jenis Masalah", "Deskripsi", "Status Laporan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 810, 350));

        Stakeholder.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        Stakeholder.setForeground(new java.awt.Color(0, 102, 102));
        Stakeholder.setText("Kelola Data Laporan");
        jPanel1.add(Stakeholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 270, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
         try {
        // Input tanggal laporan otomatis (hari ini)
        java.util.Date tanggal = new java.util.Date();

        String lokasi = JOptionPane.showInputDialog(this, "Masukkan Lokasi Laporan:");
        if (lokasi == null || lokasi.isEmpty()) return;

        String jenis = JOptionPane.showInputDialog(this, "Masukkan Jenis Masalah:");
        if (jenis == null || jenis.isEmpty()) return;

        String deskripsi = JOptionPane.showInputDialog(this, "Masukkan Deskripsi:");
        if (deskripsi == null || deskripsi.isEmpty()) return;

        String[] statusOptions = {"Baru", "Diproses", "Selesai"};
String status = (String) JOptionPane.showInputDialog(
    this,
    "Pilih Status Laporan:",
    "Status Laporan",
    JOptionPane.QUESTION_MESSAGE,
    null,
    statusOptions,
    statusOptions[0]
);
if (status == null) return; // batal jika user cancel



        // Buat objek laporan baru
        Laporan l = new Laporan();
        l.setTanggalLaporan(tanggal);
        l.setLokasiLaporan(lokasi);
        l.setJenisMasalah(jenis);
        l.setDeskripsi(deskripsi);
        l.setStatusLaporan(status);

        if (laporanDAO.tambahLaporan(l)) {
            JOptionPane.showMessageDialog(this, "✅ Laporan berhasil ditambahkan!");
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Gagal menambah laporan!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }   
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data laporan yang ingin diedit terlebih dahulu!");
        return;
    }

    try {
        int idLaporan = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        Laporan laporan = laporanDAO.getById(idLaporan);
        if (laporan == null) {
            JOptionPane.showMessageDialog(this, "Data laporan tidak ditemukan di database!");
            return;
        }

        // Form input data
        String lokasi = JOptionPane.showInputDialog(this, "Lokasi Laporan:", laporan.getLokasiLaporan());
        if (lokasi == null) return;

        String jenis = JOptionPane.showInputDialog(this, "Jenis Masalah:", laporan.getJenisMasalah());
        if (jenis == null) return;

        String deskripsi = JOptionPane.showInputDialog(this, "Deskripsi:", laporan.getDeskripsi());
        if (deskripsi == null) return;

        String[] opsiStatus = {"Baru", "Diproses", "Selesai"};
        JComboBox<String> combo = new JComboBox<>(opsiStatus);
        combo.setSelectedItem(laporan.getStatusLaporan());
        int hasil = JOptionPane.showConfirmDialog(this, combo, "Pilih Status Laporan:", JOptionPane.OK_CANCEL_OPTION);
        if (hasil != JOptionPane.OK_OPTION) return;
        String statusDipilih = (String) combo.getSelectedItem();

        // Set data baru
        laporan.setLokasiLaporan(lokasi);
        laporan.setJenisMasalah(jenis);
        laporan.setDeskripsi(deskripsi);
        laporan.setStatusLaporan(statusDipilih);

        // Update database
        if (laporanDAO.updateLaporan(laporan)) {
            JOptionPane.showMessageDialog(this, "Laporan berhasil diperbarui!");
            loadData(); // refresh tabel
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui laporan!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
                                  
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
         int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih laporan yang ingin dihapus!");
            return;
        }

        int id = (int) model.getValueAt(row, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah yakin ingin menghapus laporan ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            if (laporanDAO.hapusLaporan(id)) {
                JOptionPane.showMessageDialog(this, "Laporan berhasil dihapus!");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus laporan!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSubmitMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakatActionPerformed
        this.dispose();
    if ("superadmin".equalsIgnoreCase(currentRole)) {
        new AdminForm().setVisible(true); // super admin kembali ke menu 3 tombol
    } else {
        new LoginForm().setVisible(true); // sub admin kembali ke form login
    }
    }//GEN-LAST:event_btnSubmitMasyarakatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaLaporanForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Stakeholder;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSubmitMasyarakat;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private boolean jenis() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
