/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.AkunPenggunaDAO;
import dao.AkunPenggunaDAOImpl;
import database.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import model.AkunPengguna;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Admin;
import model.Masyarakat;
import model.Stakeholder;   

/**
 *
 * @author aliya
 */
public class KelolaPenggunaForm extends javax.swing.JFrame {
    private static final Logger logger = Logger.getLogger(LoginForm.class.getName());
    private AkunPenggunaDAO akunDAO;
    private final Connection conn;
    private DefaultTableModel model;
    
    
    public KelolaPenggunaForm() {
    initComponents();
    try {
        conn = DatabaseConnection.getConnection();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "❌ Gagal terhubung ke database: " + e.getMessage());
        throw new RuntimeException("Koneksi database gagal", e);
    }
    akunDAO = new AkunPenggunaDAOImpl();
    model = (DefaultTableModel) jTable2.getModel();
    loadData();
}
    public boolean updateAkun(AkunPengguna akun) {
    String sql = "UPDATE akun_pengguna SET username=?, password=?, role=?, alamat=?, kontak=? WHERE id_akun=?";
    try (PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setString(1, akun.getUsername());
        ps.setString(2, akun.getPassword());
        ps.setString(3, akun.getRole());
        ps.setString(4, akun.getAlamat());
        ps.setString(5, akun.getKontak());
        ps.setInt(6, akun.getIdAkun());
        return ps.executeUpdate() > 0;
    } catch (SQLException e) {
        e.printStackTrace();
        return false;
    }
    }

    public boolean hapusAkun(int id) {
    String sql = "DELETE FROM akun_pengguna WHERE id_akun=?";
    try (PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setInt(1, id);
        return ps.executeUpdate() > 0;
    } catch (SQLException e) {
        e.printStackTrace();
        return false;
    }
    }

    private void loadData() {
        model.setRowCount(0); // hapus semua baris dulu
        List<AkunPengguna> akunList = akunDAO.getAllAkun();
        for (AkunPengguna akun : akunList) {
            model.addRow(new Object[]{
                akun.getIdAkun(),
                akun.getUsername(),
                akun.getPassword(),
                akun.getRole(),
                akun.getAlamat(),
                akun.getKontak(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSubmitMasyarakat = new javax.swing.JButton();
        Stakeholder = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 465));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTambah.setBackground(new java.awt.Color(0, 102, 102));
        btnTambah.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, 30));

        btnEdit.setBackground(new java.awt.Color(0, 102, 102));
        btnEdit.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 90, 30));

        btnHapus.setBackground(new java.awt.Color(0, 102, 102));
        btnHapus.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 90, 30));

        btnSubmitMasyarakat.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat.setText("KELUAR");
        btnSubmitMasyarakat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakatActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 90, 30));

        Stakeholder.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        Stakeholder.setForeground(new java.awt.Color(0, 102, 102));
        Stakeholder.setText("Kelola Data Pengguna");
        jPanel1.add(Stakeholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 270, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID_Akun", "Username", "Password", "Role", "Alamat", "Kontak"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 810, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
     String username = JOptionPane.showInputDialog(this, "Masukkan Username:");
    if (username == null || username.isEmpty()) return;

    String password = JOptionPane.showInputDialog(this, "Masukkan Password:");
    if (password == null || password.isEmpty()) return;

    String[] roles = {"masyarakat", "stakeholder"};
String role = (String) JOptionPane.showInputDialog(
    this,
    "Pilih Role Pengguna:",
    "Role",
    JOptionPane.QUESTION_MESSAGE,
    null,
    roles,
    roles[0]
);
if (role == null) return;


    String alamat = JOptionPane.showInputDialog(this, "Masukkan Alamat:");
    if (alamat == null || alamat.isEmpty()) return;

    String kontak = JOptionPane.showInputDialog(this, "Masukkan Kontak:");
    if (kontak == null || kontak.isEmpty()) return;

    AkunPengguna akun;
    switch (role.toLowerCase()) {
    case "admin" -> {
        Admin admin = new Admin(username, password);
        admin.setAlamat(alamat);
        admin.setKontak(kontak);
        admin.setJabatan("Petugas");
        admin.setStatusAdmin("Aktif");
        admin.setWewenang("Penuh");
        akun = admin;
    }
    case "masyarakat" -> {
        Masyarakat m = new Masyarakat(username, password, alamat);
        m.setKontak(kontak);
        akun = m;
    }
    case "stakeholder" -> {
        Stakeholder s = new Stakeholder(username, password, alamat, kontak);
        akun = s;
    }
    default -> {
        JOptionPane.showMessageDialog(this, "Role tidak valid! Gunakan: admin / masyarakat / stakeholder");
        return;
    }
}


    if (akunDAO.tambahAkun(akun)) {
        JOptionPane.showMessageDialog(this, "✅ Akun berhasil ditambahkan!");
        loadData();
    } else {
        JOptionPane.showMessageDialog(this, "❌ Gagal menambah akun!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         int row = jTable2.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Pilih akun yang ingin diedit terlebih dahulu!");
        return;
    }

    int id = (int) model.getValueAt(row, 0);
    String currentUsername = (String) model.getValueAt(row, 1);
    String currentPassword = (String) model.getValueAt(row, 2);
    String currentRole = (String) model.getValueAt(row, 3);
    String currentAlamat = (String) model.getValueAt(row, 4);
    String currentKontak = (String) model.getValueAt(row, 5);

    String username = JOptionPane.showInputDialog(this, "Edit Username:", currentUsername);
    if (username == null || username.isEmpty()) return;

    String password = JOptionPane.showInputDialog(this, "Edit Password:", currentPassword);
    if (password == null || password.isEmpty()) return;

    // 🔹 Ganti input role manual jadi JComboBox
    String[] opsiRole = {"masyarakat", "stakeholder"};
    JComboBox<String> comboRole = new JComboBox<>(opsiRole);
    comboRole.setSelectedItem(currentRole);

    int hasil = JOptionPane.showConfirmDialog(
        this,
        comboRole,
        "Pilih Role Pengguna:",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    if (hasil != JOptionPane.OK_OPTION) return;
    String roleDipilih = (String) comboRole.getSelectedItem();

    String alamat = JOptionPane.showInputDialog(this, "Edit Alamat:", currentAlamat);
    if (alamat == null || alamat.isEmpty()) return;

    String kontak = JOptionPane.showInputDialog(this, "Edit Kontak:", currentKontak);
    if (kontak == null || kontak.isEmpty()) return;

    // 🔹 Buat objek akun baru sesuai role
    AkunPengguna akun;
    switch (roleDipilih.toLowerCase()) {
        case "masyarakat" -> akun = new Masyarakat(username, password, alamat);
        case "stakeholder" -> akun = new Stakeholder(username, password, alamat, kontak);
        default -> {
            JOptionPane.showMessageDialog(this, "Role tidak valid!");
            return;
        }
    }

    akun.setIdAkun(id);
    akun.setAlamat(alamat);
    akun.setKontak(kontak);

    // 🔹 Simpan ke database
    if (akunDAO.updateAkun(akun)) {
        JOptionPane.showMessageDialog(this, "Data akun berhasil diperbarui!");
        loadData();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui akun!", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_btnEditActionPerformed
    
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih akun yang ingin dihapus!");
            return;
        }
        int id = (int) model.getValueAt(row, 0);
        if (akunDAO.hapusAkun(id)) {
            JOptionPane.showMessageDialog(this, "Akun berhasil dihapus!");
            loadData();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menghapus akun!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSubmitMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakatActionPerformed
        new AdminForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KelolaPenggunaForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Stakeholder;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSubmitMasyarakat;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
