/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import model.AkunPengguna;

/**
 *
 * @author aliya
 */
public class LoginStakeholderForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(LoginStakeholderForm.class.getName());

    private final AkunPengguna akun; // akun aktif (bisa null untuk preview)

    // === Konstruktor untuk dipakai setelah login ===
    public LoginStakeholderForm(AkunPengguna akun, String jenisFromDB) {
    this.akun = akun;
    initComponents();
    setJenisStakeholderSelected(jenisFromDB);
    setTitle("Stakeholder • " + (akun != null ? akun.getUsername() : ""));
}
public void setJenisStakeholderSelected(String jenis) {
    if (jenis == null) return;
    for (int i = 0; i < jComboBox1.getItemCount(); i++) {
        if (jComboBox1.getItemAt(i).equalsIgnoreCase(jenis)) {
            jComboBox1.setSelectedIndex(i);
            break;
        }
    }
}


    // === Konstruktor default untuk preview/designer ===
    public LoginStakeholderForm() {
        this.akun = null;
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSubmitMasyarakat3 = new javax.swing.JButton();
        Username1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 465));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitMasyarakat3.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat3.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat3.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat3.setText("LOGOUT");
        btnSubmitMasyarakat3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 120, 30));

        Username1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 50)); // NOI18N
        Username1.setForeground(new java.awt.Color(0, 102, 102));
        Username1.setText("Stakeholder");
        Username1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 280, 70));

        btnLogin.setBackground(new java.awt.Color(0, 102, 102));
        btnLogin.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("OK");
        btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 100, 30));

        Username.setText("Jenis Stakeholder");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinas Lingkungan Hidup", "Perguruan Tinggi", "Komunitas Lingkungan" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 340, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String selected = jComboBox1.getSelectedItem().toString();

        if (selected.equalsIgnoreCase("Dinas Lingkungan Hidup")) {
            new MenuStakeholderExtendedForm().setVisible(true);
        } else if (selected.equalsIgnoreCase("Perguruan Tinggi") ||
               selected.equalsIgnoreCase("Komunitas Lingkungan")) {
            new MenuStakeholderBasicForm().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Silakan pilih jenis stakeholder terlebih dahulu!");
        }

        this.dispose();           
//        new MenuStakeholderExtendedForm().setVisible(true);
//        this.dispose();
//        
    
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSubmitMasyarakat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat3ActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakat3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginStakeholderForm().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSubmitMasyarakat3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
