/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ASUS
 */
public class MenuStakeholderBasicForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuStakeholderBasicForm.class.getName());

    /**
     * Creates new form MenuStakeholderBasicForm
     */
    public MenuStakeholderBasicForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubmitMasyarakat1 = new javax.swing.JButton();
        btnSubmitMasyarakat2 = new javax.swing.JButton();
        btnSubmitMasyarakat = new javax.swing.JButton();
        Username1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnSubmitMasyarakat1.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat1.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat1.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat1.setText("PROGRAM KOLABORASI");
        btnSubmitMasyarakat1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitMasyarakat2.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat2.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat2.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat2.setText("PROGRAM KOLABORASI");
        btnSubmitMasyarakat2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmitMasyarakat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 200, 30));

        btnSubmitMasyarakat.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat.setText("LAPORAN KEGIATAN");
        btnSubmitMasyarakat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakatActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmitMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 200, 30));

        Username1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 50)); // NOI18N
        Username1.setForeground(new java.awt.Color(0, 102, 102));
        Username1.setText("Hi Stakeholder!");
        Username1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 350, 90));

        jButton1.setBackground(new java.awt.Color(255, 204, 252));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Keluar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/8.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 991, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitMasyarakat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat1ActionPerformed
        new ProgramKolaborasiForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakat1ActionPerformed

    private void btnSubmitMasyarakat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat2ActionPerformed
        new ProgramKolaborasiForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakat2ActionPerformed

    private void btnSubmitMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakatActionPerformed
        new LaporanKegiatanForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new LoginStakeholderForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuStakeholderBasicForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username1;
    private javax.swing.JButton btnSubmitMasyarakat;
    private javax.swing.JButton btnSubmitMasyarakat1;
    private javax.swing.JButton btnSubmitMasyarakat2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
