/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.AkunPengguna;
/**
 *
 * @author aliya
 */
public class MenuStakeholderExtendedForm extends javax.swing.JFrame {
private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(MenuStakeholderExtendedForm.class.getName());

    private final AkunPengguna akun;

    public MenuStakeholderExtendedForm(AkunPengguna akun) {
        this.akun = akun;
        initComponents();
        setTitle("Menu Stakeholder (Extended) • " + (akun != null ? akun.getUsername() : ""));
    }

    public MenuStakeholderExtendedForm() { // designer
        this.akun = null;
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSubmitMasyarakat3 = new javax.swing.JButton();
        btnSubmitMasyarakat2 = new javax.swing.JButton();
        btnSubmitMasyarakat = new javax.swing.JButton();
        btnSubmitMasyarakat1 = new javax.swing.JButton();
        Username1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 465));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitMasyarakat3.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat3.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        btnSubmitMasyarakat3.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat3.setText("Keluar");
        btnSubmitMasyarakat3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 120, 30));

        btnSubmitMasyarakat2.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat2.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat2.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat2.setText("MANAJEMEN TPS");
        btnSubmitMasyarakat2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 200, 30));

        btnSubmitMasyarakat.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat.setText("LAPORAN KEGIATAN");
        btnSubmitMasyarakat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakatActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 200, 30));

        btnSubmitMasyarakat1.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat1.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat1.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat1.setText("PROGRAM KOLABORASI");
        btnSubmitMasyarakat1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 480, 200, 30));

        Username1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 50)); // NOI18N
        Username1.setForeground(new java.awt.Color(0, 102, 102));
        Username1.setText("Hi Stakeholder!");
        Username1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 350, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakatActionPerformed
        new LaporanKegiatanForm().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakatActionPerformed

    private void btnSubmitMasyarakat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat1ActionPerformed
        new ProgramKolaborasiForm().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakat1ActionPerformed

    private void btnSubmitMasyarakat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat2ActionPerformed
        new TPSForm().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakat2ActionPerformed

    private void btnSubmitMasyarakat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat3ActionPerformed
        new LoginStakeholderForm().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakat3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuStakeholderExtendedForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Username1;
    private javax.swing.JButton btnSubmitMasyarakat;
    private javax.swing.JButton btnSubmitMasyarakat1;
    private javax.swing.JButton btnSubmitMasyarakat2;
    private javax.swing.JButton btnSubmitMasyarakat3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
