/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.LaporanDAO;
import dao.LaporanDAOImpl;
import model.Laporan;
import model.AkunPengguna;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aliya
 */
public class PelaporanMasyarakatForm extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(PelaporanMasyarakatForm.class.getName());
    private LaporanDAO laporanDAO;
    private AkunPengguna akun;
    private DefaultTableModel model;


    public PelaporanMasyarakatForm(AkunPengguna akun) {
    initComponents();
    this.akun = akun;
    laporanDAO = new LaporanDAOImpl();

    // ✅ Inisialisasi model tabel sebelum loadData()
    model = (DefaultTableModel) jTable1.getModel();

    // Optional: pastikan kolom sesuai
    model.setColumnIdentifiers(new Object[]{
        "Tanggal", "Lokasi", "Jenis Masalah", "Deskripsi", "Status"
    });

    loadData();
}


    // ✅ Konstruktor kosong (optional)
    public PelaporanMasyarakatForm() {
        this(null);
    }

    private void loadData() {
    if (model == null) {
        System.err.println("⚠️ Model tabel belum diinisialisasi!");
        return;
    }

    model.setRowCount(0); // hapus isi tabel lama

    for (Laporan l : laporanDAO.getAllLaporan()) {
        model.addRow(new Object[]{
            l.getTanggalLaporan(),
            l.getLokasiLaporan(),
            l.getJenisMasalah(),
            l.getDeskripsi(),
            l.getStatusLaporan()
        });
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSubmitMasyarakat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtDeskripsi = new javax.swing.JTextField();
        Deskripsi = new javax.swing.JLabel();
        txtJenisMasalah = new javax.swing.JTextField();
        JenisMasalah = new javax.swing.JLabel();
        txtLokasi = new javax.swing.JTextField();
        LokasiLaporan = new javax.swing.JLabel();
        TanggalLaporan = new javax.swing.JLabel();
        Masyarakat = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnSubmitMasyarakat1 = new javax.swing.JButton();
        btnSubmitMasyarakat2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 465));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTambah.setBackground(new java.awt.Color(0, 102, 102));
        btnTambah.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 90, 30));

        btnEdit.setBackground(new java.awt.Color(0, 102, 102));
        btnEdit.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 90, 30));

        btnHapus.setBackground(new java.awt.Color(0, 102, 102));
        btnHapus.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 90, 30));

        btnSubmitMasyarakat.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat.setText("LOGOUT");
        btnSubmitMasyarakat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakatActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 90, 30));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setForeground(new java.awt.Color(0, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tanggal", "Lokasi", "Jenis Masalah", "Deskripsi"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 830, 210));

        txtDeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeskripsiActionPerformed(evt);
            }
        });
        jPanel1.add(txtDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 310, 30));

        Deskripsi.setText("Deskripsi");
        jPanel1.add(Deskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 130, 20));

        txtJenisMasalah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisMasalahActionPerformed(evt);
            }
        });
        jPanel1.add(txtJenisMasalah, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, 310, 30));

        JenisMasalah.setText("Jenis Masalah");
        jPanel1.add(JenisMasalah, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 160, -1));

        txtLokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLokasiActionPerformed(evt);
            }
        });
        jPanel1.add(txtLokasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 310, 30));

        LokasiLaporan.setText("Lokasi Laporan");
        jPanel1.add(LokasiLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 160, -1));

        TanggalLaporan.setText("Tanggal Laporan");
        jPanel1.add(TanggalLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 170, 20));

        Masyarakat.setFont(new java.awt.Font("Berlin Sans FB", 1, 26)); // NOI18N
        Masyarakat.setForeground(new java.awt.Color(0, 102, 102));
        Masyarakat.setText("Pelaporan Masyarakat");
        jPanel1.add(Masyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 310, 40));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 310, 30));

        btnSubmitMasyarakat1.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat1.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat1.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat1.setText("LOGOUT");
        btnSubmitMasyarakat1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 90, 30));

        btnSubmitMasyarakat2.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat2.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        btnSubmitMasyarakat2.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat2.setText("Lihat Profil");
        btnSubmitMasyarakat2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLokasiActionPerformed

    private void txtJenisMasalahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisMasalahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisMasalahActionPerformed

    private void txtDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeskripsiActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
         try {
        java.util.Date tanggal = jDateChooser1.getDate();
        if (tanggal == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silakan pilih tanggal laporan!");
            return;
        }

        String lokasi = txtLokasi.getText().trim();
        String jenis = txtJenisMasalah.getText().trim();
        String deskripsi = txtDeskripsi.getText().trim();

        if (lokasi.isEmpty() || jenis.isEmpty() || deskripsi.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Semua field wajib diisi!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        int idAkun = (akun != null) ? akun.getIdAkun() : 1;

        Laporan laporan = new Laporan(
            tanggal,
            lokasi,
            jenis,
            deskripsi,
            "Menunggu Konfirmasi",
            idAkun,
            0
        );
        laporan.setIdMasyarakat(idAkun);

        if (laporanDAO.tambahLaporan(laporan)) {
            javax.swing.JOptionPane.showMessageDialog(this, "✅ Laporan berhasil dikirim!");
            loadData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "❌ Gagal menambah laporan!");
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!");
        return;
    }

    try {
        // Ambil laporan yang dipilih
        Laporan laporan = laporanDAO.getAllLaporan().get(selectedRow);

        // Tampilkan pop-up edit
        EditLaporanDialog dialog = new EditLaporanDialog(this, laporan);
        dialog.setVisible(true);

        // Jika user menekan "Simpan"
        if (dialog.isSaved()) {
            if (laporanDAO.updateLaporan(laporan)) {
                JOptionPane.showMessageDialog(this, "✅ Laporan berhasil diubah!");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Gagal mengubah laporan!");
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
    }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus laporan ini?", "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        int idLaporan = laporanDAO.getAllLaporan().get(selectedRow).getIdPelapor();
        if (laporanDAO.hapusLaporan(idLaporan)) {
            javax.swing.JOptionPane.showMessageDialog(this, "🗑️ Laporan berhasil dihapus!");
            loadData();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "❌ Gagal menghapus laporan!");
        }
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnSubmitMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakatActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this,
        "Apakah Anda yakin ingin logout?",
        "Konfirmasi Logout",
        javax.swing.JOptionPane.YES_NO_OPTION,
        javax.swing.JOptionPane.QUESTION_MESSAGE
    );

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnSubmitMasyarakatActionPerformed

    private void btnSubmitMasyarakat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubmitMasyarakat1ActionPerformed

    private void btnSubmitMasyarakat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat2ActionPerformed
        if (akun != null) {
        new ProfilMasyarakatForm(akun).setVisible(true);
        this.dispose(); // jika ingin menutup menu pelaporan saat lihat profil
    } else {
        JOptionPane.showMessageDialog(this, "Data akun tidak ditemukan!");
    }
    }//GEN-LAST:event_btnSubmitMasyarakat2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        AkunPengguna akun = null;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PelaporanMasyarakatForm(akun).setVisible(true));
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Deskripsi;
    private javax.swing.JLabel JenisMasalah;
    private javax.swing.JLabel LokasiLaporan;
    private javax.swing.JLabel Masyarakat;
    private javax.swing.JLabel TanggalLaporan;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSubmitMasyarakat;
    private javax.swing.JButton btnSubmitMasyarakat1;
    private javax.swing.JButton btnSubmitMasyarakat2;
    private javax.swing.JButton btnTambah;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtJenisMasalah;
    private javax.swing.JTextField txtLokasi;
    // End of variables declaration//GEN-END:variables

}
