/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.ProgramKolaborasiDAO;
import dao.ProgramKolaborasiDAOImpl;
import model.ProgramKolaborasi;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Logger;


public class ProgramKolaborasiForm extends javax.swing.JFrame {
    private int selectedIdProgram = -1;
    private static final Logger logger = Logger.getLogger(ProgramKolaborasiForm.class.getName());
    private final ProgramKolaborasiDAO programDAO = new ProgramKolaborasiDAOImpl();

    public ProgramKolaborasiForm() {
        initComponents();
        loadDataProgram();
    }

    private void loadDataProgram() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    for (ProgramKolaborasi p : programDAO.getAllPrograms()) {
        model.addRow(new Object[]{
            p.getIdProgram(),
            p.getNamaProgram(),
            p.getDeskripsi(),
            p.getTanggalMulai(),
            p.getTanggalSelesai(),
            p.getStatusProgram()
        });
    }
}



    // ==================== CRUD HANDLER ==================== //




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSubmitMasyarakat = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        StatusProgram = new javax.swing.JLabel();
        TanggalSelesai = new javax.swing.JLabel();
        TanggalMulai = new javax.swing.JLabel();
        txtDeskripsi = new javax.swing.JTextField();
        Deskripsi = new javax.swing.JLabel();
        txtNamaProgram = new javax.swing.JTextField();
        NamaProgram = new javax.swing.JLabel();
        Stakeholder = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 465));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitMasyarakat.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat.setText("KELUAR");
        btnSubmitMasyarakat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakatActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 120, 30));

        jComboBox1.setBackground(new java.awt.Color(192, 192, 192));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perencanaan", "Berjalan", "Selesai" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, 120, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setForeground(new java.awt.Color(0, 102, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Program", "Deskripsi", "Tanggal Mulai", "Tanggal Selesai", "Status Program"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 480, 350));

        btnHapus.setBackground(new java.awt.Color(0, 102, 102));
        btnHapus.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 90, 30));

        btnEdit.setBackground(new java.awt.Color(0, 102, 102));
        btnEdit.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 90, 30));

        btnTambah.setBackground(new java.awt.Color(0, 102, 102));
        btnTambah.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 90, 30));

        StatusProgram.setText("Status Program");
        jPanel1.add(StatusProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 130, 20));

        TanggalSelesai.setText("Tanggal Selesai");
        jPanel1.add(TanggalSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 130, 20));

        TanggalMulai.setText("Tanggal Mulai");
        jPanel1.add(TanggalMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 160, 20));

        txtDeskripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeskripsiActionPerformed(evt);
            }
        });
        jPanel1.add(txtDeskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 270, 20));

        Deskripsi.setText("Deskripsi");
        jPanel1.add(Deskripsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 160, 20));

        txtNamaProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaProgramActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamaProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 270, 20));

        NamaProgram.setText(" Nama Program");
        jPanel1.add(NamaProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 170, 20));

        Stakeholder.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        Stakeholder.setForeground(new java.awt.Color(0, 102, 102));
        Stakeholder.setText("Program Kolaborasi");
        jPanel1.add(Stakeholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 240, 40));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 270, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 270, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaProgramActionPerformed

    private void txtDeskripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeskripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeskripsiActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
        if (txtNamaProgram.getText().isEmpty() || txtDeskripsi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua data harus diisi!");
            return;
        }

        ProgramKolaborasi p = new ProgramKolaborasi();
        p.setNamaProgram(txtNamaProgram.getText());
        p.setDeskripsi(txtDeskripsi.getText());
        p.setTanggalMulai(new java.sql.Date(jDateChooser1.getDate().getTime()));
        p.setTanggalSelesai(new java.sql.Date(jDateChooser2.getDate().getTime()));
        p.setStatusProgram((String) jComboBox1.getSelectedItem());

        ProgramKolaborasiDAO dao = new ProgramKolaborasiDAOImpl();
        if (dao.addProgram(p)) {
            JOptionPane.showMessageDialog(this, "✅ Program berhasil ditambahkan!");
            loadDataProgram();
        } else {
            JOptionPane.showMessageDialog(this, "❌ Gagal menambahkan program!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
          if (selectedIdProgram == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data terlebih dahulu!");
        return;
    }

    ProgramKolaborasi p = new ProgramKolaborasi();
    p.setIdProgram(selectedIdProgram);
    p.setNamaProgram(txtNamaProgram.getText());
    p.setDeskripsi(txtDeskripsi.getText());
    p.setTanggalMulai(new java.sql.Date(jDateChooser1.getDate().getTime()));
    p.setTanggalSelesai(new java.sql.Date(jDateChooser2.getDate().getTime()));
    p.setStatusProgram(jComboBox1.getSelectedItem().toString());

    ProgramKolaborasiDAO dao = new ProgramKolaborasiDAOImpl();
    if (dao.updateProgram(p)) {
        JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
        loadDataProgram();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal memperbarui data!");
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
         if (selectedIdProgram == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
        return;
    }

    ProgramKolaborasiDAO dao = new ProgramKolaborasiDAOImpl();
    if (dao.deleteProgram(selectedIdProgram)) {
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        loadDataProgram();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal menghapus data!");
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnSubmitMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakatActionPerformed
        new MenuStakeholderExtendedForm().setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_btnSubmitMasyarakatActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         int baris = jTable1.getSelectedRow();
    if (baris != -1) {
        selectedIdProgram = Integer.parseInt(jTable1.getValueAt(baris, 0).toString());
        txtNamaProgram.setText(jTable1.getValueAt(baris, 1).toString());
        txtDeskripsi.setText(jTable1.getValueAt(baris, 2).toString());
        jDateChooser1.setDate(java.sql.Date.valueOf(jTable1.getValueAt(baris, 3).toString()));
        jDateChooser2.setDate(java.sql.Date.valueOf(jTable1.getValueAt(baris, 4).toString()));
        jComboBox1.setSelectedItem(jTable1.getValueAt(baris, 5).toString());
    }
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProgramKolaborasiForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Deskripsi;
    private javax.swing.JLabel NamaProgram;
    private javax.swing.JLabel Stakeholder;
    private javax.swing.JLabel StatusProgram;
    private javax.swing.JLabel TanggalMulai;
    private javax.swing.JLabel TanggalSelesai;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSubmitMasyarakat;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtNamaProgram;
    // End of variables declaration//GEN-END:variables
}
