/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.RegistController;
import javax.swing.JOptionPane;
/**
 *
 * @author aliya
 */
public class RegistForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistForm.class.getName());
    private javax.swing.JComboBox<String> comboRole;

    /**
     * Creates new form MasyarakatForm
     */
    
    public RegistForm() {
        initComponents();
        comboRole = new javax.swing.JComboBox<>(new String[] {
    "Stakeholder", "Masyarakat"
});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSubmitMasyarakat1 = new javax.swing.JButton();
        Username2 = new javax.swing.JLabel();
        Username1 = new javax.swing.JLabel();
        btnSubmitMasyarakat = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox<>();
        Role = new javax.swing.JLabel();
        Alamat1 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        Kontak1 = new javax.swing.JLabel();
        txtKontak = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 465));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmitMasyarakat1.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat1.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat1.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat1.setText("KEMBALI");
        btnSubmitMasyarakat1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakat1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 120, 30));

        Username2.setBackground(new java.awt.Color(153, 204, 255));
        Username2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Username2.setForeground(new java.awt.Color(255, 255, 255));
        Username2.setText("Sudah punya akun?");
        jPanel1.add(Username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 160, 30));

        Username1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 50)); // NOI18N
        Username1.setForeground(new java.awt.Color(0, 102, 102));
        Username1.setText("Registrasi");
        Username1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 230, 70));

        btnSubmitMasyarakat.setBackground(new java.awt.Color(255, 204, 252));
        btnSubmitMasyarakat.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        btnSubmitMasyarakat.setForeground(new java.awt.Color(0, 102, 102));
        btnSubmitMasyarakat.setText("LOGIN");
        btnSubmitMasyarakat.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitMasyarakat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMasyarakatActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmitMasyarakat, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 120, 30));

        Username.setText("Username");
        jPanel1.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 80, -1));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 320, -1));

        Password.setText("Password");
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 80, -1));

        jComboBoxRole.setBackground(new java.awt.Color(192, 192, 192));
        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masyarakat", "Stakeholder" }));
        jComboBoxRole.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRoleActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 320, -1));

        Role.setText("Role");
        jPanel1.add(Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 50, -1));

        Alamat1.setText("Alamat");
        jPanel1.add(Alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 60, -1));

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 320, -1));

        Kontak1.setText("Kontak");
        jPanel1.add(Kontak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 60, -1));

        txtKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKontakActionPerformed(evt);
            }
        });
        jPanel1.add(txtKontak, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 320, -1));

        btnRegister.setBackground(new java.awt.Color(0, 102, 102));
        btnRegister.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("REGISTER");
        btnRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 170, 30));

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 320, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 980, 640));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 652, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String username = txtUsername.getText().trim();
    String password = new String(jPasswordField1.getPassword()).trim();
    String alamat = txtAlamat.getText().trim();
    String kontak = txtKontak.getText().trim();
    String role = jComboBoxRole.getSelectedItem().toString();

    if (kontak.length() > 15) {
        JOptionPane.showMessageDialog(this, "Nomor kontak maksimal 15 karakter!");
        return;
    }

    RegistController controller = new RegistController();
    boolean success = controller.register(username, password, alamat, kontak, role);

    if (success) {
        JOptionPane.showMessageDialog(this, "Akun berhasil didaftarkan!");
        new LoginForm().setVisible(true);
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Gagal registrasi! Periksa kembali input Anda.");
    }

    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKontakActionPerformed

    private void btnSubmitMasyarakatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakatActionPerformed
            new LoginForm().setVisible(true);  
        this.dispose();                     
    }//GEN-LAST:event_btnSubmitMasyarakatActionPerformed

    private void jComboBoxRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRoleActionPerformed

    private void btnSubmitMasyarakat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMasyarakat1ActionPerformed
           new MenuUtamaForm().setVisible(true); 
        this.dispose(); 
       
    }//GEN-LAST:event_btnSubmitMasyarakat1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat1;
    private javax.swing.JLabel Kontak1;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Role;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username1;
    private javax.swing.JLabel Username2;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSubmitMasyarakat;
    private javax.swing.JButton btnSubmitMasyarakat1;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtKontak;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
